services:
  # What to call the service hosting the site. Because there is only
  # one service, it is automatically set as the default service, which
  # does a few things
  #   1. Clones the git repository into the service container
  #   2. Exposes port 80 to the Tugboat HTTP proxy
  #   3. Routes requests to the preview URL to this service
  apache:
    # Use the available version of Apache by not specifying a version
    image: tugboatqa/httpd

    # A set of commands to run while building this service
    commands:
      # Commands that set up the basic preview infrastructure
      init:
        # Install system dependency packages
        - sudo apt update && sudo apt install ruby-full build-essential zlib1g-dev
        # Link the document root to the expected path
        - ln -snf "${TUGBOAT_ROOT}/_site" "${DOCROOT}"

      # Commands that import data or other assets into a service
      update:
        # Install ruby gem dependencies
        - gem install bundler jekyll
        - bundle install

      # Commands that build or generate the actual site
      build:
        # Build the static website to _site/
        - bundle exec jekyll build
